### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by artkernelzyc** [LGCooci/libclosure-74-KCBuild#1]
![image](https://user-images.githubusercontent.com/9601701/101307881-76352e00-3883-11eb-8312-130fba04f1aa.png)

**Comment by LGCooci** [comment]
你的系统版本是多少？你这个错误应该build错了 scheme请使用KC Build发自我的iPhone------------------ 原始邮件 ------------------发件人: artkernelzyc  <notifications@github.com>发送时间: 2020年12月7日 11:58收件人: LGCooci/libclosure-74-KCBuild <libclosure-74-KCBuild@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[LGCooci/libclosure-74-KCBuild] 编译错误 (#1)


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/LGCooci/libclosure-74-KCBuild/issues/1",
"url": "https://github.com/LGCooci/libclosure-74-KCBuild/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
